development:
  facebook:
    key: 421566044622499
    secret: 9df1b0ca9405a97a21a44cc2902f9eab
  twitter:
    key: RFeL8EJn3V7K00E12QYU7g
    secret: FngMw3BkJxBxVaLVKUVBeMMPCt3QG8GHWLEIQSgY
  wordpress:
    key: 8488
    secret: x5fj7ofeB4bcwozpwJ6YJR9z21OFFePnxoI0SXoT6FZhEB2dLHT82urqg6LzIGvQ

